#!/usr/bin/env python3
"""
Add/refresh two cheap-insurance SEO tags in <head> on every real content
page: a canonical URL and a standard <meta name="description">.

Why: the site already carries og:description/twitter:description (added
in a prior pass) but no plain <meta name="description"> — the tag Google's
organic snippet actually prefers — and no canonical tags at all, which is
free protection against trailing-slash/parameter/www-vs-apex duplicates.

Source of truth: the existing og:description content on each page (never
invents new copy) and the page's own path (for the canonical URL).
og:description/twitter:description are left at their full length (fine
for social preview cards); <meta name="description"> is trimmed to
whole sentences that fit Google's ~155-160 character SERP snippet —
never invents a shorter sentence, just selects a natural prefix of the
existing text, always keeping at least the first full sentence even if
it alone runs over budget.

For a page whose first sentence alone still runs over budget, a
hand-written replacement can be added to
data/meta-description-overrides.json (keyed by the page's relative
path) — used only for <meta name="description">, never touching the
on-page copy or og:description/twitter:description.

Injects between clearly marked comment delimiters, idempotent — safe to
re-run any time a page's og:description changes.

Deliberately excludes: 404.html (left as-is per project decision),
redirect stubs like `recipe-pages/savory-libyan-kaak.html` (no
og:description to source from), and anything outside the site
(e.g. `from webflow/`, gitignored reference export).

Usage:
  python3 scripts/add_seo_tags.py              # process every page
  python3 scripts/add_seo_tags.py --only PATH  # process a single page,
                                                 # e.g. recipe-pages/pizza.html
  python3 scripts/add_seo_tags.py --check       # report only, write nothing
"""
import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://sweetsaltyrecipes.com"
OVERRIDES_FILE = ROOT / "data" / "meta-description-overrides.json"

BEGIN_MARKER = "<!-- BEGIN SEO TAGS (auto-generated by scripts/add_seo_tags.py — do not edit by hand) -->"
END_MARKER = "<!-- END SEO TAGS -->"

EXCLUDE = {"404.html", "recipe-pages/savory-libyan-kaak.html"}

META_DESCRIPTION_LIMIT = 157


def load_overrides():
    if not OVERRIDES_FILE.exists():
        return {}
    return json.loads(OVERRIDES_FILE.read_text(encoding="utf-8"))


def shorten_for_meta(text, limit=META_DESCRIPTION_LIMIT):
    """As many whole sentences as fit within `limit` chars, always keeping
    at least the first sentence even if it alone runs over — a slightly
    long but complete sentence beats a hard mid-word cutoff."""
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    result = sentences[0]
    for sentence in sentences[1:]:
        candidate = f"{result} {sentence}"
        if len(candidate) <= limit:
            result = candidate
        else:
            break
    return result


def discover_pages():
    pages = []
    for pattern in ("*.html", "recipe-pages/*.html", "collection-pages/*.html"):
        for p in sorted(ROOT.glob(pattern)):
            rel = p.relative_to(ROOT).as_posix()
            if rel in EXCLUDE:
                continue
            pages.append(rel)
    return pages


def canonical_url(rel_path):
    # The homepage canonicalizes to the clean root URL, not /index.html —
    # cheap insurance against a duplicate being indexed under both forms.
    if rel_path == "index.html":
        return f"{SITE_URL}/"
    return f"{SITE_URL}/{rel_path}"


def build_block(rel_path, page_html, overrides):
    if rel_path in overrides:
        short_text = overrides[rel_path]
    else:
        m = re.search(r'<meta property="og:description" content="(.*?)">', page_html)
        if not m:
            return None, f"no og:description found on {rel_path} to source the meta description from"
        full_text = html.unescape(m.group(1))
        short_text = shorten_for_meta(full_text)
    escaped = short_text.replace("&", "&amp;").replace('"', "&quot;")
    canonical = canonical_url(rel_path)
    block = (
        f"{BEGIN_MARKER}\n"
        f'<link rel="canonical" href="{canonical}">\n'
        f'<meta name="description" content="{escaped}">\n'
        f"{END_MARKER}"
    )
    return block, None


def inject(page_html, block):
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if pattern.search(page_html):
        return pattern.sub(block, page_html)
    # Insert right after <title>...</title> — the conventional spot for
    # canonical/description, ahead of the OG/Twitter block. A function
    # replacement avoids re.sub's backslash-escape handling in `block`.
    new_html, n = re.subn(r"</title>", lambda m: m.group(0) + "\n" + block, page_html, count=1)
    if n == 0:
        sys.exit("ERROR: no <title> tag found to anchor insertion")
    return new_html


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="process a single page by relative path")
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    args = ap.parse_args()

    pages = discover_pages()
    if args.only:
        pages = [p for p in pages if p == args.only]
        if not pages:
            sys.exit(f"ERROR: '{args.only}' not found among discovered pages")

    overrides = load_overrides()

    written, blocked = [], []
    for rel_path in pages:
        path = ROOT / rel_path
        page_html = path.read_text(encoding="utf-8")
        block, problem = build_block(rel_path, page_html, overrides)
        if problem:
            blocked.append((rel_path, problem))
            continue
        new_html = inject(page_html, block)
        if not args.check and new_html != page_html:
            path.write_text(new_html, encoding="utf-8")
        written.append(rel_path)

    print(f"\n{'Would add' if args.check else 'Added'} canonical + meta description to {len(written)} page(s):")
    for p in written:
        print(f"  ✓ {p}")

    if blocked:
        print(f"\nSkipped {len(blocked)} page(s):")
        for p, problem in blocked:
            print(f"  ✗ {p} — {problem}")
        sys.exit(1)


if __name__ == "__main__":
    main()
