#!/usr/bin/env python3
"""
Generate/refresh Recipe JSON-LD structured data on every recipe-pages/*.html
page, from data that already exists on the site plus a hand-maintained
data/recipe-meta.json for values that genuinely cannot be derived.

Sources of truth (never invents data):
  - js/main.js            -> ALL_RECIPES array: title, image, tags
  - recipe-pages/*.html   -> description, ingredients, instructions
                              (parsed from the existing DOM structure)
  - data/recipe-meta.json -> prepTime, cookTime, totalTime, recipeYield,
                              author, datePublished (hand-maintained; these
                              cannot be reliably derived from the page)
  - git history           -> dateModified: the page file's last commit date
                              (`git log -1`), so it stays accurate as recipes
                              are edited without anyone having to hand-update
                              it. Falls back to datePublished for a file with
                              no commit history yet (e.g. a brand-new page).

Idempotent: re-running replaces the block between the delimiter comments
in place. Never touches anything outside those delimiters.

Usage:
  python3 scripts/generate_schema.py              # process all recipe pages
  python3 scripts/generate_schema.py --only SLUG  # process a single page
                                                    #   (SLUG = filename
                                                    #   without .html, e.g.
                                                    #   italian-s-cookies)
  python3 scripts/generate_schema.py --check       # report only, write nothing
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parent.parent
MAIN_JS = ROOT / "js" / "main.js"
META_JSON = ROOT / "data" / "recipe-meta.json"
RECIPE_DIR = ROOT / "recipe-pages"
SITE_URL = "https://sweetsaltyrecipes.com"

BEGIN_MARKER = "<!-- BEGIN RECIPE SCHEMA (auto-generated by scripts/generate_schema.py — do not edit by hand) -->"
END_MARKER = "<!-- END RECIPE SCHEMA -->"

REQUIRED_META_FIELDS = [
    "prepTime", "cookTime", "totalTime", "recipeYield", "author", "datePublished",
]

TYPE_TAGS = {"Cookie", "Pastry", "Cake", "Dessert", "Breakfast"}
DIFFICULTY_TAGS = {"Easy", "Moderate", "Hard"}
SWEET_SALTY_TAGS = {"Sweet", "Salty"}
CUISINE_ADJECTIVE = {
    "Italy": "Italian",
    "France": "French",
    "USA": "American",
    "Germany": "German",
    "Denmark": "Danish",
    "Austria": "Austrian",
    "Netherlands": "Dutch",
    "Middle East": "Middle Eastern",
}


def parse_all_recipes(js_text):
    """Extract the ALL_RECIPES array from js/main.js.

    The array is hand-formatted as one object literal per line with a
    consistent shape (see js/main.js), so a per-line regex is simpler and
    more transparent than pulling in a JS parser dependency for a file we
    control ourselves.
    """
    m = re.search(r"const ALL_RECIPES = \[(.*?)\n\];", js_text, re.DOTALL)
    if not m:
        sys.exit("ERROR: could not find `const ALL_RECIPES = [...]` in js/main.js")

    recipes = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue

        def field(name):
            fm = re.search(name + r":\s*(['\"])(.*?)\1", line)
            return fm.group(2) if fm else None

        title = field("title")
        img = field("img")
        page = field("page")
        date = field("date")
        desc = field("desc")
        tags_m = re.search(r"tags:\s*\[(.*?)\]", line)
        tags = [t.strip().strip("'\"") for t in tags_m.group(1).split(",")] if tags_m else []

        if not (title and img and page):
            sys.exit(f"ERROR: could not parse an ALL_RECIPES entry — line was:\n{line}")

        recipes.append({
            "title": title, "img": img, "page": page, "tags": tags, "date": date, "desc": desc,
        })
    return recipes


def slug_for(page_path):
    return Path(page_path).stem


def git_last_commit_date(page_path):
    """Last commit date (YYYY-MM-DD) touching this file, or None if git has
    no history for it yet (untracked / brand-new file)."""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--", page_path],
            cwd=ROOT, capture_output=True, text=True, timeout=5, check=True,
        )
    except (subprocess.SubprocessError, OSError):
        return None
    date = result.stdout.strip()
    return date or None


def derive_category_cuisine_keywords(tags):
    category = next((t for t in tags if t in TYPE_TAGS), None)
    cuisine_tag = next(
        (t for t in tags if t not in TYPE_TAGS and t not in DIFFICULTY_TAGS and t not in SWEET_SALTY_TAGS),
        None,
    )
    cuisine = CUISINE_ADJECTIVE.get(cuisine_tag, cuisine_tag) if cuisine_tag else None
    keywords = ", ".join(tags)
    return category, cuisine, keywords


def extract_ingredients(soup):
    heading = next(
        (h for h in soup.select("h3.recipe-section-title") if h.get_text(strip=True) == "Ingredients"),
        None,
    )
    if heading is None:
        return None, "no <h3 class=\"recipe-section-title\">Ingredients</h3> found"

    ingredients = []
    for sib in heading.find_next_siblings():
        if sib.name == "h3":
            break
        if sib.name == "ul" and "ingredients-list" in sib.get("class", []):
            for li in sib.find_all("li"):
                text = re.sub(r"\s+", " ", li.get_text(" ", strip=True)).strip()
                if text:
                    ingredients.append(text)

    if not ingredients:
        return None, "found the Ingredients heading but no ingredients-list <li> items after it"
    return ingredients, None


def extract_instructions(soup):
    ol = soup.select_one("ol.instructions-list")
    if ol is None:
        return None, "no <ol class=\"instructions-list\"> found"

    steps = []
    for li in ol.find_all("li", recursive=False):
        step_content = li.select_one(".step-content")
        if step_content is None:
            continue
        title_el = step_content.select_one(".step-title")
        title = re.sub(r"\s+", " ", title_el.get_text(" ", strip=True)).strip() if title_el else ""
        # Text of step-content minus the title, i.e. the description that
        # follows <strong class="step-title">...</strong>.
        full_text = re.sub(r"\s+", " ", step_content.get_text(" ", strip=True)).strip()
        text = full_text[len(title):].strip() if title and full_text.startswith(title) else full_text
        if not text:
            text = full_text
        steps.append({"@type": "HowToStep", "name": title, "text": text})

    if not steps:
        return None, "found <ol class=\"instructions-list\"> but no usable steps inside it"
    return steps, None


def extract_description(soup):
    el = soup.select_one(".recipe-hero-desc")
    return el.get_text(strip=True) if el else None


def build_jsonld(recipe, meta, soup):
    problems = []

    for field in REQUIRED_META_FIELDS:
        if not meta.get(field, "").strip():
            problems.append(f"data/recipe-meta.json[\"{slug_for(recipe['page'])}\"].{field} is empty")

    description = extract_description(soup)
    if not description:
        problems.append("no .recipe-hero-desc found on the page for `description`")

    ingredients, ing_err = extract_ingredients(soup)
    if ing_err:
        problems.append(ing_err)

    instructions, instr_err = extract_instructions(soup)
    if instr_err:
        problems.append(instr_err)

    if problems:
        return None, problems

    category, cuisine, keywords = derive_category_cuisine_keywords(recipe["tags"])
    date_modified = git_last_commit_date(recipe["page"]) or meta["datePublished"]

    jsonld = {
        "@context": "https://schema.org",
        "@type": "Recipe",
        "name": recipe["title"],
        "image": [f"{SITE_URL}/{recipe['img']}"],
        "description": description,
        "author": {"@type": "Organization", "name": meta["author"]},
        "datePublished": meta["datePublished"],
        "dateModified": date_modified,
        "prepTime": meta["prepTime"],
        "cookTime": meta["cookTime"],
        "totalTime": meta["totalTime"],
        "recipeYield": meta["recipeYield"],
        "recipeIngredient": ingredients,
        "recipeInstructions": instructions,
    }
    if category:
        jsonld["recipeCategory"] = category
    if cuisine:
        jsonld["recipeCuisine"] = cuisine
    if keywords:
        jsonld["keywords"] = keywords

    return jsonld, []


def inject(html, jsonld):
    block = (
        f"{BEGIN_MARKER}\n"
        f"<script type=\"application/ld+json\">\n"
        f"{json.dumps(jsonld, indent=2, ensure_ascii=False)}\n"
        f"</script>\n"
        f"{END_MARKER}"
    )
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if pattern.search(html):
        return pattern.sub(block, html)
    return html.replace("</head>", f"{block}\n</head>")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="process a single recipe by slug (filename without .html)")
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    args = ap.parse_args()

    all_recipes = parse_all_recipes(MAIN_JS.read_text(encoding="utf-8"))
    meta_all = json.loads(META_JSON.read_text(encoding="utf-8"))

    # Structural check first: every recipe in ALL_RECIPES must have an entry
    # in recipe-meta.json at all (a missing *entry*, as opposed to an empty
    # field, is a hard stop rather than a per-recipe skip).
    missing_entries = [
        slug_for(r["page"]) for r in all_recipes if slug_for(r["page"]) not in meta_all
    ]
    if missing_entries:
        sys.exit(
            "ERROR: data/recipe-meta.json is missing entries for: "
            + ", ".join(sorted(missing_entries))
        )

    if args.only:
        all_recipes = [r for r in all_recipes if slug_for(r["page"]) == args.only]
        if not all_recipes:
            sys.exit(f"ERROR: no ALL_RECIPES entry with slug '{args.only}'")

    written, blocked = [], []
    for recipe in all_recipes:
        slug = slug_for(recipe["page"])
        page_path = ROOT / recipe["page"]
        if not page_path.exists():
            blocked.append((slug, [f"page file not found: {recipe['page']}"]))
            continue

        html = page_path.read_text(encoding="utf-8")
        soup = BeautifulSoup(html, "html.parser")
        meta = meta_all[slug]

        jsonld, problems = build_jsonld(recipe, meta, soup)
        if problems:
            blocked.append((slug, problems))
            continue

        new_html = inject(html, jsonld)
        if not args.check and new_html != html:
            page_path.write_text(new_html, encoding="utf-8")
        written.append(slug)

    print(f"\n{'Would generate' if args.check else 'Generated'} JSON-LD for {len(written)} page(s):")
    for slug in written:
        print(f"  ✓ {slug}")

    if blocked:
        print(f"\nSkipped {len(blocked)} page(s) — missing data (fix and re-run):")
        for slug, problems in blocked:
            print(f"  ✗ {slug}")
            for p in problems:
                print(f"      - {p}")
        sys.exit(1)


if __name__ == "__main__":
    main()
