#!/usr/bin/env python3
"""
Pull the last 28 days of Search Console data for sweetsaltyrecipes.com and write
a ranked-list report to reports/. Plain data pull and formatting — no LLM
calls, no interpretation.

Produces three lists:
  - Content gaps:      high impressions, near-zero clicks (query x page)
  - Striking distance:  average position 8-20 (query x page)
  - Working:            top pages by clicks (page only)

Auth: a Google Cloud service account with Search Console API access,
granted "Full" or "Restricted" access to the sweetsaltyrecipes.com property in
Search Console (Settings > Users and permissions > Add user, using the
service account's email). See README.md in this directory for the full
one-time setup.

Credentials are read from environment variables only — never hardcoded,
never committed:
  GSC_SERVICE_ACCOUNT_FILE  path to the service account's JSON key file
  GSC_SITE_URL              the property as verified in Search Console,
                             e.g. "https://sweetsaltyrecipes.com/" (URL-prefix
                             property — matches how this site is verified)

Usage:
  export GSC_SERVICE_ACCOUNT_FILE=/path/to/key.json
  export GSC_SITE_URL=https://sweetsaltyrecipes.com/
  python3 scripts/search_console_report.py
"""
import datetime
import os
import sys
from pathlib import Path

from google.oauth2 import service_account
from googleapiclient.discovery import build

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "reports"
SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]

# Content gaps: impressions at or above this, clicks at or below this.
GAP_MIN_IMPRESSIONS = 50
GAP_MAX_CLICKS = 1
# Striking distance: average position within this range.
STRIKING_MIN_POSITION = 8
STRIKING_MAX_POSITION = 20
TOP_N = 25


def get_credentials():
    key_path = os.environ.get("GSC_SERVICE_ACCOUNT_FILE")
    if not key_path:
        sys.exit("ERROR: GSC_SERVICE_ACCOUNT_FILE environment variable is not set.")
    if not Path(key_path).exists():
        sys.exit(f"ERROR: GSC_SERVICE_ACCOUNT_FILE points to a file that doesn't exist: {key_path}")
    return service_account.Credentials.from_service_account_file(key_path, scopes=SCOPES)


def get_site_url():
    site_url = os.environ.get("GSC_SITE_URL")
    if not site_url:
        sys.exit("ERROR: GSC_SITE_URL environment variable is not set.")
    return site_url


def query_search_analytics(service, site_url, start_date, end_date, dimensions, row_limit=25000):
    body = {
        "startDate": start_date,
        "endDate": end_date,
        "dimensions": dimensions,
        "rowLimit": row_limit,
    }
    response = service.searchanalytics().query(siteUrl=site_url, body=body).execute()
    return response.get("rows", [])


def content_gaps(query_page_rows):
    gaps = [
        r for r in query_page_rows
        if r["impressions"] >= GAP_MIN_IMPRESSIONS and r["clicks"] <= GAP_MAX_CLICKS
    ]
    gaps.sort(key=lambda r: r["impressions"], reverse=True)
    return gaps[:TOP_N]


def striking_distance(query_page_rows):
    striking = [
        r for r in query_page_rows
        if STRIKING_MIN_POSITION <= r["position"] <= STRIKING_MAX_POSITION
    ]
    striking.sort(key=lambda r: r["impressions"], reverse=True)
    return striking[:TOP_N]


def working_pages(page_rows):
    ranked = sorted(page_rows, key=lambda r: r["clicks"], reverse=True)
    return ranked[:TOP_N]


def md_table_query_page(rows):
    if not rows:
        return "_None found for this period._\n"
    lines = [
        "| Query | Page | Clicks | Impressions | CTR | Avg. position |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        query, page = r["keys"]
        ctr = f"{r['ctr'] * 100:.1f}%"
        lines.append(
            f"| {query} | {page} | {r['clicks']} | {r['impressions']} | {ctr} | {r['position']:.1f} |"
        )
    return "\n".join(lines) + "\n"


def md_table_page(rows):
    if not rows:
        return "_None found for this period._\n"
    lines = [
        "| Page | Clicks | Impressions | CTR | Avg. position |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in rows:
        (page,) = r["keys"]
        ctr = f"{r['ctr'] * 100:.1f}%"
        lines.append(f"| {page} | {r['clicks']} | {r['impressions']} | {ctr} | {r['position']:.1f} |")
    return "\n".join(lines) + "\n"


def build_report(start_date, end_date, gaps, striking, working):
    return f"""# Search Console report — {start_date} to {end_date}

Generated by `scripts/search_console_report.py`. Raw data pull, no interpretation applied.

## Content gaps
Queries with {GAP_MIN_IMPRESSIONS}+ impressions but {GAP_MAX_CLICKS} or fewer clicks — visible in search, not getting clicked. Candidates for a better title/description match, or the page not actually answering the query.

{md_table_query_page(gaps)}

## Striking distance
Queries ranking at position {STRIKING_MIN_POSITION}-{STRIKING_MAX_POSITION} — close enough that a small on-page improvement could push them onto page 1.

{md_table_query_page(striking)}

## Working
Top pages by clicks over this period — what's actually bringing traffic in right now.

{md_table_page(working)}
"""


def main():
    credentials = get_credentials()
    site_url = get_site_url()
    service = build("searchconsole", "v1", credentials=credentials)

    end_date = datetime.date.today()
    start_date = end_date - datetime.timedelta(days=28)
    start_str, end_str = start_date.isoformat(), end_date.isoformat()

    query_page_rows = query_search_analytics(
        service, site_url, start_str, end_str, dimensions=["query", "page"]
    )
    page_rows = query_search_analytics(
        service, site_url, start_str, end_str, dimensions=["page"]
    )

    report = build_report(
        start_str, end_str,
        content_gaps(query_page_rows),
        striking_distance(query_page_rows),
        working_pages(page_rows),
    )

    REPORTS_DIR.mkdir(exist_ok=True)
    out_path = REPORTS_DIR / f"{end_str}-search-console.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
